ebi-ait/dcp-ingest-central#313: Added wrangling status and wrangler filters to `All Projects` page
ebi-ait/ingest-ui pull request #103
Opened 2021-07-08 10:17 UTC by yusra-haider

2021-07-09 08:58 UTC, amnonkhen submitted a review, later dismissed

2021-07-09 10:11 UTC, ke4 approved these changes
Looks fine by me 👍  💯

2021-07-09 15:15 UTC, ke4 submitted a review, later dismissed

2021-07-09 15:54 UTC, amnonkhen approved these changes

2021-07-19 16:52 UTC, amnonkhen requested changes

2021-07-19 16:52 UTC, amnonkhen commented on client/src/app/all-projects/all-projects.component.html
> +    <mat-select placeholder="Filter by status" (selectionChange)="onFilterByState($event)">
status or state?

2021-07-19 16:52 UTC, amnonkhen commented on client/src/app/all-projects/all-projects.component.ts
> +import * as ingestSchema from '../project-form/project-ingest-schema.json';
I would organise the imports alphabetically as well as group by library imports and our own imports. the IDE can do it for you.

2021-07-19 16:52 UTC, amnonkhen commented on client/src/app/all-projects/all-projects.component.ts
> +        pagedData.data = data._embedded ? data._embedded.projects : [];
You could use the elvis operator here.
```suggestion
        pagedData.data = data._embedded?.projects || [];
```

2021-07-20 08:55 UTC, yusra-haider commented on client/src/app/all-projects/all-projects.component.html
> +    <mat-select placeholder="Filter by status" (selectionChange)="onFilterByState($event)">
as per the UI designs, it's `status`

2021-07-21 12:27 UTC, amnonkhen approved these changes

2021-07-21 12:47 UTC, aaclan-ebi approved these changes

2021-07-21 13:04 UTC, merged