Force yarn
ebi-ait/ingest-ui pull request #111
Opened 2021-07-29 13:03 UTC by jacobwindsor

2021-07-29 13:17 UTC, amnonkhen submitted a review, later dismissed

2021-08-05 16:08 UTC, amnonkhen commented on client/package.json
> +    "staging": "ng ser  ve -c staging",
looks like a mistake

2021-08-05 16:08 UTC, amnonkhen requested changes
possible syntax errors

2021-09-06 10:37 UTC, amnonkhen approved these changes

2021-09-20 12:25 UTC, aaclan-ebi approved these changes

2021-09-20 12:41 UTC, yusra-haider approved these changes

2021-09-20 12:54 UTC, merged