set cookie before response/err from broker
ebi-ait/ingest-ui pull request #148
Opened 2021-12-20 15:06 UTC by prabh-t

2021-12-20 15:14 UTC, aaclan-ebi approved these changes

2021-12-20 15:18 UTC, jacobwindsor approved these changes

2021-12-20 16:06 UTC, amnonkhen requested changes

2021-12-20 16:06 UTC, amnonkhen commented on src/app/submission/pages/submission.component.ts
> +    this.cookieService.set(this.DOWNLOAD_TIMEOUT_COOKIE, "1", {expires: this.DOWNLOAD_BACKOFF_MINS / (24*60)})
Instead of using a comment to specify intent, a properly named function can be used.

2022-01-06 16:23 UTC, merged

2022-01-12 14:37 UTC, MightyAx commented on src/app/submission/pages/submission.component.ts
> +      this.cookieService.delete(this.DOWNLOAD_TIMEOUT_COOKIE);
This line broke the unit tests but I've [fixed them](https://github.com/ebi-ait/ingest-ui/commit/a26bbadacc2f1a6a73605e01d8b9672559cf7523).