Dcp 547 project wrangling status history
ebi-ait/ingest-ui pull request #172
Opened 2022-04-29 08:25 UTC by yusra-haider

2022-05-05 12:19 UTC, jacobwindsor approved these changes

2022-05-05 15:34 UTC, ke4 approved these changes

2022-05-06 12:36 UTC, amnonkhen requested changes

2022-05-06 12:36 UTC, amnonkhen commented on src/app/projects/components/audit-log/audit-log.component.ts
> +    return `${auditLog['auditType']} from ${this.formatAuditEvent(auditLog['before'])} to ${
The audit log should be formatted as a table.

2022-05-06 12:36 UTC, amnonkhen commented on src/app/projects/components/audit-log/audit-log.component.ts
> +  formatAuditDate(date: string): string {
This kind of formatting is usually done in the html template rather than in code.
See https://www.npmjs.com/package/ngx-pipes

2022-05-06 12:36 UTC, amnonkhen commented on src/app/projects/components/audit-log/audit-log.component.ts
> +    return (event ? startCase(lowerCase(event)) : 'None');
This kind of formatting is usually done in the html template rather than in code.
See https://www.npmjs.com/package/ngx-pipes

2022-05-06 12:37 UTC, amnonkhen approved these changes

2022-05-09 10:29 UTC, merged